Remove trailing whitespace; and untabify some mixed tabs/spaces

diff --git a/ratt b/ratt
--- a/ratt
+++ b/ratt
@@ -66,84 +66,84 @@ then
 fi
 
 if [ ! -z "$RATT_VERBOSE" ]
-	then
-	verbose=1;
+        then
+        verbose=1;
 fi
 
 if [ -z "$RATT_DOTRANSLATION" ] ;
-	then
-	RATT_DOTRANSLATION=0	
+        then
+        RATT_DOTRANSLATION=0
 fi
 
 ### nucmer call as function
 function doNucmer {
 sleep 10
-	if [ ! -z "$verbose" ] 
-		then 
-		echo "nucmer  $other_nucmer  -g $g -p $name -c $c -l $l $ref $query"
-		echo "delta-filter $rearrange -i $minInd $name.delta > $name.filter.delta"
-	fi
-	echo  nucmer $other_nucmer -D $D -g $g -p $name -c $c -l $l $ref $query
-	nucmer $other_nucmer -g $g -p $name -c $c -l $l $ref $query  # &> /dev/null
-	delta-filter $rearrange -i $minInd $name.delta > $name.filter.delta
-	show-snps -HTr $name.filter.delta > $name.snp
-	show-coords -clHT $name.delta > $name.coords
-	show-coords -clHT $name.filter.delta > $name.filter.coords
+        if [ ! -z "$verbose" ]
+                then
+                echo "nucmer  $other_nucmer -g $g -p $name -c $c -l $l $ref $query"
+                echo "delta-filter $rearrange -i $minInd $name.delta > $name.filter.delta"
+        fi
+        echo  nucmer $other_nucmer -D $D -g $g -p $name -c $c -l $l $ref $query
+        nucmer $other_nucmer -g $g -p $name -c $c -l $l $ref $query  # &> /dev/null
+        delta-filter $rearrange -i $minInd $name.delta > $name.filter.delta
+        show-snps -HTr $name.filter.delta > $name.snp
+        show-coords -clHT $name.delta > $name.coords
+        show-coords -clHT $name.filter.delta > $name.filter.coords
 }
 
 function doiCORN {
 
 
-	echo " embl file are in embl_DIR
- 	root is $root
+        echo " embl file are in embl_DIR
+        root is $root
     pre_embl is $pre_embl
     iteration is $iteration
 "
 
-	echo "================="
-	cd "$root$(($iteration-1))"
+        echo "================="
+        cd "$root$(($iteration-1))"
 
-	cd "$root$(($iteration-1))"
-	
+        cd "$root$(($iteration-1))"
 
-	# geneate the plot
-	mkdir plot
-	echo "Producing the coverage plots in $root$iteration"
-#	awk '{ if ($1 ~ "^cons") {print $4 > "plot/"x"."$2".plot"}}' x=Iter.$iteration <(gunzip -c *pileup.gz)
-	cd ..
-	mkdir -p RATT.$iteration/Seq
-	cd RATT.$iteration/Seq
 
-	perl $RATT_HOME/main.ratt.pl Split ../../$root.$iteration
-	
-	cd ..
-	ln -s ../$root$(($iteration-1))/plot
+        # geneate the plot
+        mkdir plot
+        echo "Producing the coverage plots in $root$iteration"
+#       awk '{ if ($1 ~ "^cons") {print $4 > "plot/"x"."$2".plot"}}' x=Iter.$iteration <(gunzip -c *pileup.gz)
+        cd ..
+        mkdir -p RATT.$iteration/Seq
+        cd RATT.$iteration/Seq
 
-	tmp=$$;
-	ln -s ../$embl_DIR embl.$tmp
+        perl $RATT_HOME/main.ratt.pl Split ../../$root.$iteration
 
-	mkdir tmp
-	for x in `grep '>' ../$root.$iteration | sed 's/>//g' | awk '{ print $1 }'` ; do
-		cat ../$root.*.$x.gff > ../All.$x.gff;
-		egrep "\"INS|\"DEL"  ../All.$x.gff | sort -n -k 4 > tmp/All.indel.$x.gff; 
-		echo "perl $RATT_HOME/ratt.icorn.pl embl.$tmp/$x.embl tmp/All.indel.$x.gff $x $x.embl 4000000"
-		perl $RATT_HOME/ratt.icorn.pl  embl.$tmp/$x.embl tmp/All.indel.$x.gff $x $x.embl 4000000 > out;
+        cd ..
+        ln -s ../$root$(($iteration-1))/plot
+
+        tmp=$$;
+        ln -s ../$embl_DIR embl.$tmp
+
+        mkdir tmp
+        for x in `grep '>' ../$root.$iteration | sed 's/>//g' | awk '{ print $1 }'` ; do
+                cat ../$root.*.$x.gff > ../All.$x.gff;
+                egrep "\"INS|\"DEL"  ../All.$x.gff | sort -n -k 4 > tmp/All.indel.$x.gff;
+                echo "perl $RATT_HOME/ratt.icorn.pl embl.$tmp/$x.embl tmp/All.indel.$x.gff $x $x.embl 4000000"
+                perl $RATT_HOME/ratt.icorn.pl  embl.$tmp/$x.embl tmp/All.indel.$x.gff $x $x.embl 4000000 > out;
 echo "perl ~/Bin/icorn.flagNonCorrectedRegions.pl Seq/$x plot/Iter.$iteration.$x.plot $x 20 100 Not+Corrected"
-		perl ~/Bin/icorn.flagNonCorrectedRegions.pl Seq/$x plot/Iter.$iteration.$x.plot $x 20 100 Not+Corrected;
-		
-	done;
+                perl ~/Bin/icorn.flagNonCorrectedRegions.pl Seq/$x plot/Iter.$iteration.$x.plot $x 20 100 Not+Corrected;
+
+        done;
 
 
 }
 
-if [ "$refembl" == "iCORN" ] ; then 
-	refembl=$2;
-	query=$3
-	result=$4
-#	doiCORN;
-#	echo done;
-#	exit;
-	parameterSet="Assembly"
+if [ "$refembl" == "iCORN" ] ; then
+        refembl=$2;
+        query=$3
+        result=$4
+#       doiCORN;
+#       echo done;
+#       exit;
+        parameterSet="Assembly"
 fi
 
 ### check path of nucmer and the perl transferprogram
@@ -153,12 +153,12 @@ EMBL_files=${EMBL_files-`ls $refembl/ | wc 2>/dev/null`}
 if (test "$NUCMER_EXE" == "");
 then
    echo "nucmer is not on the PATH"
-   exit; 
+   exit;
 elif(test "$EMBL_files" == "");
 then
    echo "Cannot find any EMBL files in $refembl is not on the PATH."
    echo "So far just embl formatted files can be used. They must end with .embl."
-   exit; 
+   exit;
 fi
 
 tmp=$$;
@@ -167,7 +167,7 @@ tmp=$$;
 if [ ! -f "$query" ]                # be sure the directory /mnt exists
   then
     echo "Query $query doesn't exist"
-	exit
+        exit
 fi
 
 # get weird character aways
@@ -176,25 +176,25 @@ query=query.$tmp
 orig_query=$query
 
 # check for the reference
-if [ -f "$ref" ] 
-	then 
-	# if the reference exist, use this
-	echo "I am using the reference $ref. Please make sure that the description line of each fasta entry is the same than in the embl file name!";
-	head -n 1 $ref
-	echo "should be the same name as the embl file in embl"
-	ls $refembl
-	echo
-	echo
+if [ -f "$ref" ]
+        then
+        # if the reference exist, use this
+        echo "I am using the reference $ref. Please make sure that the description line of each fasta entry is the same than in the embl file name!";
+        head -n 1 $ref
+        echo "should be the same name as the embl file in embl"
+        ls $refembl
+        echo
+        echo
 else
-	ref="Reference.$tmp.fasta"
-	perl $RATT_HOME/main.ratt.pl Embl2Fasta $refembl $ref
+        ref="Reference.$tmp.fasta"
+        perl $RATT_HOME/main.ratt.pl Embl2Fasta $refembl $ref
 fi
-	
+
 ### check if files ok
 if [ ! -f "$ref" ]                # be sure the directory /mnt exists
   then
     echo "Sorry the reference file wasn't generated corretly."
-	exit
+        exit
 fi;
 
 name=nucmer.$result
@@ -215,37 +215,37 @@ doneDifference=0;
 # minLength - minlength of a hit   -- not used so far...
 
 if [ "$parameterSet" == "Assembly" ] || [ "$parameterSet" == "Assembly.Repetitive" ] ;
-	then 
-	c=400;
-	l=30;
-	g=1000;
-	
-	if [ "$parameterSet" == "Assembly.Repetitive" ] ;
-		then
-		other_nucmer=" --maxmatch "
-	else
-		other_nucmer="  "
-	fi
+        then
+        c=400;
+        l=30;
+        g=1000;
+
+        if [ "$parameterSet" == "Assembly.Repetitive" ] ;
+                then
+                other_nucmer=" --maxmatch "
+        else
+                other_nucmer="  "
+        fi
 #       rearrange=" -g -o 0 ";
-	rearrange=" -r -o 5 ";
-	minInd=99;
-	
-	### get real SNP before mutate
-	doNucmer 
+        rearrange=" -r -o 5 ";
+        minInd=99;
 
-	perl $RATT_HOME/main.ratt.pl Difference  $name.snp $name.filter.coords $result
-	doneDifference=1;
+        ### get real SNP before mutate
+        doNucmer
 
-	### insert of mutation to have better anchors
-	perl $RATT_HOME/main.ratt.pl Mutate $query
-	return=$?
-	if [ "$return" != "0" ] ;
-		then 
-		echo "See Error in BBA.main script, to mutate the query for Assembly to Assembly annotation transfer."
-		exit 1;
-	fi;
-	### update name of query
-	query=$query."mutated"
+        perl $RATT_HOME/main.ratt.pl Difference  $name.snp $name.filter.coords $result
+        doneDifference=1;
+
+        ### insert of mutation to have better anchors
+        perl $RATT_HOME/main.ratt.pl Mutate $query
+        return=$?
+        if [ "$return" != "0" ] ;
+                then
+                echo "See Error in BBA.main script, to mutate the query for Assembly to Assembly annotation transfer."
+                exit 1;
+        fi;
+        ### update name of query
+        query=$query."mutated"
 elif [ "$parameterSet" == "Pacbio" ] ;
        then
         c=800;
@@ -277,6 +277,7 @@ elif [ "$parameterSet" == "Pacbio" ] ;
         fi;
         ### update name of query
         query=$query."mutated"
+
 elif [ "$parameterSet" == "PacbioG" ] ;
        then
         c=800;
@@ -310,118 +311,118 @@ elif [ "$parameterSet" == "PacbioG" ] ;
         ### update name of query
         query=$query."mutated"
 elif [ "$parameterSet" == "Falciparum" ] ||  [ "$parameterSet" == "Falciparum.Repetitive" ] ;
-	then 
-	c=400;
-	l=150;
-	g=2000;
+        then
+        c=400;
+        l=150;
+        g=2000;
 
-	if [ "$parameterSet" == "Falciparum.Repetitive" ] ;
-		then
-		other_nucmer=" --maxmatch "
-	else
-		other_nucmer="  "
-	fi
-	
-	rearrange=" -r -o 1 ";
-	minInd=90;
-	
-	### get real SNP before mutate
-#	doNucmer
+        if [ "$parameterSet" == "Falciparum.Repetitive" ] ;
+                then
+                other_nucmer=" --maxmatch "
+        else
+                other_nucmer="  "
+        fi
 
-#	perl $RATT_HOME/main.ratt.pl Difference  $name.snp $name.filter.coords $result
-	doneDifference=0;
+        rearrange=" -r -o 1 ";
+        minInd=90;
 
-	### insert of mutation to have better anchors
-#	perl $RATT_HOME/main.ratt.pl Mutate $query
-#	return=$?
-#	if [ "$return" != "0" ] ;
-#		then 
-#		echo "See Error in BBA.main script, to mutate the query for Assembly to Assembly annotation transfer."
-#		exit 1;
-#	fi;
-	### update name of query
-#	query=$query."mutated"
+        ### get real SNP before mutate
+#       doNucmer
+
+#       perl $RATT_HOME/main.ratt.pl Difference  $name.snp $name.filter.coords $result
+        doneDifference=0;
+
+        ### insert of mutation to have better anchors
+#       perl $RATT_HOME/main.ratt.pl Mutate $query
+#       return=$?
+#       if [ "$return" != "0" ] ;
+#               then
+#               echo "See Error in BBA.main script, to mutate the query for Assembly to Assembly annotation transfer."
+#               exit 1;
+#       fi;
+        ### update name of query
+#       query=$query."mutated"
 
 elif [ "$parameterSet" == "Strain" ] ||  [ "$parameterSet" == "Strain.Repetitive" ] || [ "$parameterSet" == "Strain.global" ] ||  [ "$parameterSet" == "Strain.global.Repetitive" ];
-	then 
-	c=400;
-	l=20;
-	g=500;
+        then
+        c=400;
+        l=20;
+        g=500;
 
-	if [ "$parameterSet" == "Strain.Repetitive" ] || [ "$parameterSet" == "Strain.global.Repetitive" ] ;
-		then
-		other_nucmer=" --maxmatch "
-	else
-		other_nucmer="  "
-	fi
-minInd=90;	
-	rearrange=" -r -o 1 ";
-	if  [ "$parameterSet" == "Strain.global" ] ||  [ "$parameterSet" == "Strain.global.Repetitive" ] ;
-		then
-		rearrange=" -g -o 15 ";
+        if [ "$parameterSet" == "Strain.Repetitive" ] || [ "$parameterSet" == "Strain.global.Repetitive" ] ;
+                then
+                other_nucmer=" --maxmatch "
+        else
+                other_nucmer="  "
+        fi
+minInd=90;
+        rearrange=" -r -o 1 ";
+        if  [ "$parameterSet" == "Strain.global" ] ||  [ "$parameterSet" == "Strain.global.Repetitive" ] ;
+                then
+                rearrange=" -g -o 15 ";
                 minInd=95;
-		D=10	
+                D=10
 fi
 
 
-	
-	### get real SNP before mutate
-	doNucmer
 
-	perl $RATT_HOME/main.ratt.pl Difference  $name.snp $name.filter.coords $result
-	doneDifference=1;
+        ### get real SNP before mutate
+        doNucmer
 
-	### insert of mutation to have better anchors
-	perl $RATT_HOME/main.ratt.pl Mutate $query
-	return=$?
-	if [ "$return" != "0" ] ;
-		then 
-		echo "See Error in BBA.main script, to mutate the query for Assembly to Assembly annotation transfer."
-		exit 1;
-	fi;
-	### update name of query
-	query=$query."mutated"
+        perl $RATT_HOME/main.ratt.pl Difference  $name.snp $name.filter.coords $result
+        doneDifference=1;
+
+        ### insert of mutation to have better anchors
+        perl $RATT_HOME/main.ratt.pl Mutate $query
+        return=$?
+        if [ "$return" != "0" ] ;
+                then
+                echo "See Error in BBA.main script, to mutate the query for Assembly to Assembly annotation transfer."
+                exit 1;
+        fi;
+        ### update name of query
+        query=$query."mutated"
 
 elif [ "$parameterSet" == "Species" ]  || [ "$parameterSet" == "Species.Repetitive" ] || [ "$parameterSet" == "Species.global" ]  || [ "$parameterSet" == "Species.global.Repetitive" ] ;
-	then 
-	if [ "$parameterSet" == "Species.Repetitive" ] ;
-		then
-		other_nucmer=" --maxmatch "
-	else
-	other_nucmer="  -diagdiff 10 "		
+        then
+        if [ "$parameterSet" == "Species.Repetitive" ] ;
+                then
+                other_nucmer=" --maxmatch "
+        else
+        other_nucmer="  -diagdiff 10 "
 #other_nucmer="  "
-	fi
+        fi
 
-	c=400;
-	l=10;
-	g=1000;
-	minInd=40;
- 
-	rearrange=" -r -o 5 ";
-	if  [ "$parameterSet" == "Species.global" ]  || [ "$parameterSet" == "Species.global.Repetitive" ] ;
-		then
-		rearrange=" -g -o 5 ";
-	fi
+        c=400;
+        l=10;
+        g=1000;
+        minInd=40;
+
+        rearrange=" -r -o 5 ";
+        if  [ "$parameterSet" == "Species.global" ]  || [ "$parameterSet" == "Species.global.Repetitive" ] ;
+                then
+                rearrange=" -g -o 5 ";
+        fi
 elif [ "$parameterSet" == "Multiple" ] ;
-	then 
-	c=400;
-	l=25;
-	g=1000;
-	
-	other_nucmer=" --maxmatch "
-	rearrange=" -q -o 1";
-	minInd=98;
+        then
+        c=400;
+        l=25;
+        g=1000;
+
+        other_nucmer=" --maxmatch "
+        rearrange=" -q -o 1";
+        minInd=98;
 elif [ "$parameterSet" == "Free" ] ;
-	then 
-	c=$RATT_c;
-	l=$RATT_l;
-	g=$RATT_g;
-	rearrange=$RATT_rearrange;
-	minInd=$RATT_minInd;
-	other_nucmer=$RATT_anchor;
+        then
+        c=$RATT_c;
+        l=$RATT_l;
+        g=$RATT_g;
+        rearrange=$RATT_rearrange;
+        minInd=$RATT_minInd;
+        other_nucmer=$RATT_anchor;
 else
-	echo "Plese set: Transfer type: Assembly / Strain / Species / Strain.Repetitive / Strain.global / Species.Repetitive / Species.global / Free "
-	exit
+        echo "Plese set: Transfer type: Assembly / Strain / Species / Strain.Repetitive / Strain.global / Species.Repetitive / Species.global / Free "
+        exit
 fi
 
 
@@ -430,25 +431,25 @@ doNucmer
 
 # print the synteny stats and do the difference files.
 if [ "$doneDifference" == "0" ]
-	then 
-	perl $RATT_HOME/main.ratt.pl Difference  $name.snp $name.filter.coords $result
+        then
+        perl $RATT_HOME/main.ratt.pl Difference  $name.snp $name.filter.coords $result
 fi
 
 ### do the tranfer
-if [ ! -z "$verbose" ] 
-	then
-	echo "Nucmer is done. Now transfer the annotation."
-	echo "perl $RATT_HOME/main.ratt.pl $refembl $name.snp $name.filter.coords $result"
+if [ ! -z "$verbose" ]
+        then
+        echo "Nucmer is done. Now transfer the annotation."
+        echo "perl $RATT_HOME/main.ratt.pl $refembl $name.snp $name.filter.coords $result"
 fi
 
 perl $RATT_HOME/main.ratt.pl Transfer $refembl $name.snp $name.filter.coords $result
 return=$?
 if [ "$return" != "0" ] ;
-	then 
-	echo "Sorry, the RATT transfer step did fail.\n"
-	echo "Debug information: perl $RATT_HOME/main.ratt.pl Transfer $refembl $name.snp $name.filter.coords $result";
-	pwd
-	exit 1;
+        then
+        echo "Sorry, the RATT transfer step did fail.\n"
+        echo "Debug information: perl $RATT_HOME/main.ratt.pl Transfer $refembl $name.snp $name.filter.coords $result";
+        pwd
+        exit 1;
 fi;
 
 ### do ther correction
@@ -465,24 +466,23 @@ echo "Nucmer is done. Now Correct the annotation for chromosome $nameRes."
 
 
 for nameRes in `grep '>' $query | perl -nle 's/\|/_/g;/>(\S+)/; print $1'` ; do
-	echo "work on $nameRes"
-	if [ -f "$result.$nameRes.embl" ] ; then
-		echo "************************ Correction *****"
-		perl $RATT_HOME/main.ratt.pl Correct $result.$nameRes.embl Sequences/$nameRes $result.$nameRes
-	echo "************************ "
-	else 
-		### generate empty file for the joining 
-		touch $result.$nameRes.tmp2.embl
-	fi
+        echo "work on $nameRes"
+        if [ -f "$result.$nameRes.embl" ] ; then
+                echo "************************ Correction *****"
+                perl $RATT_HOME/main.ratt.pl Correct $result.$nameRes.embl Sequences/$nameRes $result.$nameRes
+        echo "************************ "
+        else
+                ### generate empty file for the joining
+                touch $result.$nameRes.tmp2.embl
+        fi
 
-	perl $RATT_HOME/main.ratt.pl doEMBL $result.$nameRes.final $result.$nameRes.tmp2.embl Sequences/$nameRes 
-	if [ "$RATT_DOTRANSLATION" -eq 1 ] ; then
-		perl $RATT_HOME/main.ratt.pl addTranslation $result.$nameRes.final.embl
-	fi
-	echo "If you want to start artemis on this replicon:"
-	echo "art $result.$nameRes.final.embl + $result.$nameRes.Report.gff  + Query/$result.$nameRes.Mutations.gff"
+        perl $RATT_HOME/main.ratt.pl doEMBL $result.$nameRes.final $result.$nameRes.tmp2.embl Sequences/$nameRes
+        if [ "$RATT_DOTRANSLATION" -eq 1 ] ; then
+                perl $RATT_HOME/main.ratt.pl addTranslation $result.$nameRes.final.embl
+        fi
+        echo "If you want to start artemis on this replicon:"
+        echo "art $result.$nameRes.final.embl + $result.$nameRes.Report.gff  + Query/$result.$nameRes.Mutations.gff"
 
 done
 
 rm $result*embl.tmp.BBA.embl # $result.$nameRes.tmp2.embl
-
